### ISSUE TITLE
Assess performance of current code

### ISSUE THREAD

**Issue by tylerjereddy** [tylerjereddy/scipy#12]
I'd like to see the performance of the current code compared against my (admittedly still buggy) final stage code from the personal repo (https://github.com/tylerjereddy/py_sphere_Voronoi). This is mostly for "peace of mind" that the large number of changes we've made in the code base haven't adversely affected performance.

Ideally, I'd like to generate a plot comparing the performance of the two and place that in the discussion thread for the PR. I'll start working on this now.

I'll be satisfied as long as they are roughly the same. If the new code is a little bit slower that is likely okay, since it is more correct after all the bug fixes.

**Comment by tylerjereddy** [comment]
So far the new code is performing WAY slower than the old version. This will require investigation.

**Comment by tylerjereddy** [comment]
See my detailed post and the performance plot in the PR thread (https://github.com/scipy/scipy/pull/5232). Performance definitely needs to improve.

**Comment by niknow** [comment]
One immediate reason I can think of is that in the benchmark of the old code you have:

```
current_Voronoi_instance =Voronoi_utility.Voronoi_Sphere_Surface(current_array_random_generators,1.0)

start_time = time.time()
```

So you start the timer after the object has been instantiated. However, even in the old code, some calculations (notably the translation) are carried out in the constructor and are not measured here. I suggest to swap these two lines.

However, I don't think this will fully account for that phenomenon. Maybe profiling the code is a good idea.

**Comment by tylerjereddy** [comment]
The old code doesn't do much during instantiation, and the input doesn't require translation for the benchmarks. The actual Voronoi calculation does not occur until later. I bet the results for the old code would be pretty much the same even if you put the instantiation in the timer block.

Regardless, just sitting and watching the benchmark loops run (regardless of where the timer stamps are placed), it is obvious that the new code is having problems at high generator counts. Yes, obviously using `line_profiler` and so on would be a good idea. Not sure if I'll get a chance to do much with this soon. I think I was doing some fancy things with structured arrays to speed things up at certain stages--I'll have to take a good look at the new code I guess.

**Comment by niknow** [comment]
I forked your benchmark and made an lprun. You can see here

https://github.com/niknow/bench_spherical_voronoi/blob/master/new_code.txt

that 99% of the time needed goes into the list comprehension calculating the regions. Im not exactly sure to what lines of the old code it corresponds:

https://github.com/niknow/bench_spherical_voronoi/blob/master/old_code.txt

but there are some pandas calls in there - maybe this was the reason why it ran so much faster. I think about how to make this list comprehension more efficient - eventually numpy's build in functions can help here (they are used in the old code as well).

**Comment by tylerjereddy** [comment]
You'll probably want to include the sorting in the profiling scheme as well.

I did manage to factor out pandas with no performance loss, so it is probably not that specifically. But yeah, I do remember spending a lot of time trying to get the regions (and especially their sorting) done efficiently. I ended up with fairly fast code, but it was a fair number of lines I think.

**Comment by niknow** [comment]
I made a few runs locally and the sorting does'nt seem to affect the performance significantly (but I'll include it again anyway). Ok, then let's focus on that list comprehension and maybe keep in mind that some optimizations are already in the old code. ;)
