### ISSUE TITLE
PEP & Verbosity issues in SphericalVoronoi

### ISSUE THREAD

**Issue by niknow** [tylerjereddy/scipy#4]
The PEP & verbosity issues discussed for `calc_circumcenters` should be fixed in the `SphericalVoronoi` class as well. I'd be happy to take care of it.

**Comment by tylerjereddy** [comment]
Great, I've assigned the issue to you.

**Comment by niknow** [comment]
I'm just revising the constructor and was puzzled by `spherical_voronoi.py#L360`:

```
    if np.all(sphere_center_origin_offset_vector):
        self.original_point_array = points - sphere_center_origin_offset_vector
```

The `np.all` would evaluate to `True` only if all coordinates of `sphere_center_origin_offset_vector` are non-zero. For instance if this vector is `[1,0,0]`, it would be `False` and the `original_point_array` would not be translated. This is not what we want here is it? I think replacing  `np.all` by `np.any` would fix that. If you are happy, I can easily incorporate this into my revision of the constructor.

**Comment by tylerjereddy** [comment]
Sounds good--we might want a unit test for that translation issue. I thought I had made a unit test to check for a translation operation, but maybe I'm mistaken.

**Comment by niknow** [comment]
You did add a unittest for the translation issue in `test_spherical_voronoi.py#L225`:

```
random_dist_voronoi_instance = spherical_voronoi.SphericalVoronoi(self.cartesian_coord_array + 3.0,1.0,np.array([3.0,3.0,3.0]))
```

But the bug does not occur with this test vector. I agree that one should have some more elementary unittests for these things. I modified the code I used to find this bug and added it into a new Test case we can use for these kind of tests.

**Comment by niknow** [comment]
I added a unittest in 79e0930b8d770701c1669bdc1f5d0f52ada51207
