### ISSUE TITLE
unit tests running slowly

### ISSUE THREAD

**Issue by tylerjereddy** [tylerjereddy/scipy#6]
Spherical Voronoi unit tests run too slowly as of commit 33bf2255aeabf2e75745835bdf416e16664914f2

It is noticeably slower when running the full test suite: `python runtests.py -v`

**Comment by niknow** [comment]
The `setUp` of the unittest `Test_voronoi_surface_area_calculations` create a random point set of 5000 points for testing, which takes quite some time. We could reduce this temporarily to `50` or would that be a problem?

**Comment by tylerjereddy** [comment]
The % reconstitution of surface area is sensitive to the number of generators, so reducing by two orders of magnitude may cause a unit test failure.
