### ISSUE TITLE
Sorting Algorithm

### ISSUE THREAD

**Issue by niknow** [tylerjereddy/scipy#7]
As discussed, we want to revise the sorting algorithm `calc_sorted_vertices` so I'm collecting the issues with the current one: 
- Sometimes it forgets to return the region for last generator. I could reproduce this error with the following points:
  
  ```
    points = np.array([[-0.78928481, -0.16341094, 0.59188373],
        [-0.66839141, 0.73309634, 0.12578818],
        [0.32535778, -0.92476944, -0.19734181],
        [-0.90177102, -0.03785291, -0.43055335],
        [0.71781344, 0.68428936, 0.12842096],
        [-0.96064876, 0.23492353, -0.14820556],
        [0.73181537, -0.22025898, -0.6449281],
        [0.79979205, 0.54555747, 0.25039913]])
  ```
- Sometimes the sorting algorithm crashes. I could reproduce this error with the following points:

```
    points = np.array([[0, 0, 1],  [0, 0, -1], [1, 0, 0], [0, 1, 0], [0, -1, 0], [-1, 0, 0],])
```
- The datastructure returned is a dictionary. Since this is uncommon in `scipy` we want to be more compatible (as close as possible to `scipy.spatial.Voronoi`). 
- At the moment the code is a bit difficult to read and not fully compatible with PEP8.

**Comment by tylerjereddy** [comment]
Sounds good--I see you recently made some adjustments and added a test.
